from __future__ import annotations

from enum import Enum


class LinkedInConnectionWorkerStatus(str, Enum):
    REQUEST_SENT = "REQUEST_SENT"
    ALREADY_CONNECTED = "ALREADY_CONNECTED"
    REQUEST_ALREADY_PENDING = "REQUEST_ALREADY_PENDING"
    FOLLOW_ONLY = "FOLLOW_ONLY"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    UNKNOWN_STATE = "UNKNOWN_STATE"
    UNKNOWN_RESULT = "UNKNOWN_RESULT"
    FAILED = "FAILED"
