from __future__ import annotations

from enum import Enum


class LinkedInMessagingWorkerStatus(str, Enum):
    DIALOG_REACHED = "DIALOG_REACHED"
    NOT_MESSAGEABLE = "NOT_MESSAGEABLE"
    MESSAGE_BUTTON_NOT_FOUND = "MESSAGE_BUTTON_NOT_FOUND"
    DIALOG_NOT_DETECTED = "DIALOG_NOT_DETECTED"
    LOGIN_REQUIRED = "LOGIN_REQUIRED"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    MESSAGE_SENT = "MESSAGE_SENT"
    SEND_FAILED = "SEND_FAILED"
    FAILED = "FAILED"
    PREMIUM_REQUIRED = "PREMIUM_REQUIRED"
    UNKNOWN_DIALOG = "UNKNOWN_DIALOG"
