from __future__ import annotations

from app.core.config import (
    LINKEDIN_BROWSER_PROFILE_ROOT,
    LINKEDIN_DEFAULT_CONNECTION_LIMIT,
    LINKEDIN_DEFAULT_MESSAGE_LIMIT,
    LINKEDIN_DEFAULT_TIMEOUT,
    LINKEDIN_DOWNLOAD_PATH,
    LINKEDIN_DEBUG,
    LINKEDIN_ENABLED,
    LINKEDIN_HEADLESS,
    LINKEDIN_PROFILE_ROOT,
    LINKEDIN_PROXY_SERVER,
    LINKEDIN_STEALTH_ENABLED,
    LINKEDIN_USER_AGENT,
    LINKEDIN_VIEWPORT_HEIGHT,
    LINKEDIN_VIEWPORT_WIDTH,
)
